spring:
  application:
  name: vendas-varejista-ponto-venda
  profiles:
    active: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pontovenda
    username: venda
    password: 12345678
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
    hibernate:
      ddl-auto: update
    properties: 
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true
  swagger-ui.path: /ponto-venda-documentacao
  api-docs.path: /ponto-venda-api-docs
  packages-to-scan: br.com.fastcloudsolucoes.pontovenda
  swagger-ui.tryItOutEnabled: true
  swagger-ui.operationsSorter: method
  swagger-ui.tagsSorter: alpha
  swagger-ui.filter: true
  
api-doc:
  openapi:
    dev-url: http://localhost:8080
